---
title: "Strawberries 1"
author: "Paul Moon"
date: "10/7/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)  
library(kableExtra)
library(tidyverse)
library(stringr)
```

```{r}
#<READ>
#A lot of the code in this homework was used from USDA-NASS data cleaning-ver2.qmd that was given to us. 

#The reason for this is because I thought that the qmd contained information of the solutions of this homework. Therefore, I decided to use this homework assignment as practice to get used to the new types of code that were shown. Thus, I decided to try and replicate and understand the qmd. My code is what I thought could make the code better/what my approach would have been and, in addition, I commented on all the codes of what I was happening in the code.

#THEN. After I finished reviewing the qmd and learning the contents within it. I worked on splitting the DOMAIN CATEGORY column into three different new columns called "Chemical", "Pesticide", and "Number" which was what the main point of the homework was (and that is at the bottom).
```

```{r}
#This is to read the data that we were supposed to use.
strawberry <- read_csv("strawberries25_v3.csv", col_names = TRUE)
glimpse(strawberry)
```

```{r}
#We first look at the entire data set and then test to see whether or not the column has a single variable or not
oneCol <- function(df){
  drop <- NULL  
  for(i in 1:dim(df)[2]){     
    if((df |> distinct(df[, i]) |> count()) == 1){
      drop = c(drop, i)
     } 
  }

#We write the outputs of the dropped columns
if(is.null(drop)){
  return("None")
  }
else{
  #I decided to take out the outputs since it was messy and unneeded.
  strawberry <- df[, -1 * drop]
  }
}

#Here we get the new columns that we worked with and input that into our data set.
strawberry <- oneCol(strawberry)
```

```{r}
#Recollecting the data to use in our separate_wider_delim
strawberry <- strawberry |>

#Here, we separate the columns by category and make the data set "wider" by the listed names
separate_wider_delim(cols = `Data Item`, delim = ",", 
                     names = c("Fruit", "Category", "Item", "Metric"), 
                     too_many = "error", too_few = "align_start")
#Did not understand this format of separate_wider_delim with the too_many and too_few until now.

#This is to change the old categories into the new trimmed category that deleted any extra space.
strawberry$Category <- str_trim(strawberry$Category, side = "both")
strawberry$Item <- str_trim(strawberry$Item, side = "both")
strawberry$Metric <- str_trim(strawberry$Metric, side = "both")

sales <- strawberry |> filter(Program == "CENSUS")
chem <- strawberry |> filter(Program == "SURVEY")
nrow(strawberry) == (nrow(chem) + nrow(sales))
```

```{r}
#Plotting some data.
straw1 <- strawberry |> 
#Setting up pulling out our data from the data set
  select(c(Year, State, Category, Value)) |> 
#For my example, I wanted to use the year 2019.
  filter((Year == 2019) & (Category == "ORGANIC - OPERATIONS WITH SALES"))

straw1$Value <- as.numeric(straw1$Value)
straw1 <- straw1 |> arrange(desc(Value))
#This reorder allows us to make the graph cleaner because it orders them in size order.
ggplot(straw1, aes(reorder(State, -Value), Value)) + 
  geom_bar(stat = "identity") + 
#This is used to make the axis more readable
  theme(axis.text.x = element_text(angle = 45,hjust = 1)) +
  labs(x = "States", y = "Operations",
title ="Organic Strawberry Operations in 2019")


straw2 <- strawberry |> 
#Again, setting up pulling out our data from the data set
  select(c(Year, State, Category, Item, Value)) |> 
  filter((Year == 2019) & (Category == "ORGANIC - SALES") & 
           (Item == "MEASURED IN $") & (Value != "(D)"))

straw2$Value <- as.numeric(gsub(",", "", straw2$Value))
straw2 <- straw1 |> arrange(desc(Value))
#This reorder allows us to make the graph cleaner because it orders them in size order.
ggplot(straw2, aes(reorder(State, -Value), Value)) + 
  geom_bar(stat = "identity") + 
  theme(axis.text.x = element_text(angle = 45,hjust = 1)) +
  labs(x = "States", y = "Sales",
title ="Organic Strawberry Sales in 2019")
```

```{r}
strawberry <- read_csv("strawberries25_v3.csv", col_names = TRUE, show_col_types = FALSE)

#I modified the DOMAIN CATEGORY into three different categories.
strawberry <- strawberry %>%
  mutate(`Domain Category` = ifelse(is.na(`Domain Category`), "", `Domain Category`)) %>%
  mutate(
    Chemical = gsub(", .*", "", `Domain Category`), 
#Get the first part before the comma
    Pesticide = gsub(".*, (.*):.*", "\\1", `Domain Category`),
#Get the second part before the colon
    Number = gsub(".*= (\\d+).*", "\\1", `Domain Category`)
#Get the number after '='
  )

print(strawberry)
```